services:
  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: geo-ranker-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      # Add your Open-Meteo API settings here if needed
      - OPEN_METEO_BASE_URL=https://api.open-meteo.com/v1
      - OPEN_METEO_LOCALE_URL=https://geocoding-api.open-meteo.com/v1
      - OPEN_METEO_MARINE_URL=https://marine-api.open-meteo.com/v1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - geo-ranker-network

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: geo-ranker-client
    ports:
      - "3000:80"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - geo-ranker-network

networks:
  geo-ranker-network:
    driver: bridge

# Optional: Add volumes for development
# volumes:
#   node_modules_server:
#   node_modules_client: